services:
  worker:
    build:
      context: ./worker
      dockerfile: container/Dockerfile
    volumes:
      - ./worker:/app
      - /app/node_modules
    depends_on:
      - redis
      - postgres
      - minio
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      MINIO_ENDPOINT: minio
  postgres:
    image: postgres:16
    container_name: fp-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: file_processor

    ports:
      - "5433:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: fp-redis
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight:latest
    container_name: fp-redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis

  minio:
    image: minio/minio
    container_name: fp-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
  postgres-data:
